/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.sou.cs452.lab3j;

// import edu.sou.cs452.lab3j.part1.*;
// import edu.sou.cs452.lab3j.part2.*;
import edu.sou.cs452.lab3j.part3.*;

public class App {
    public String getGreeting() {
        Animal[] animals = { new Cow("Bessie"), new Snake("Python", 0.5), new Fish(true) };

        // We use StringBuilder to concatenate strings efficiently.
        // This is faster than using the '+' operator because strings are immutable in Java,
        // meaning that every time you concatenate strings with '+', a new string object is created.
        // In contrast, StringBuilder allows you to modify the string without creating new objects.
        StringBuilder sb = new StringBuilder();

        // Parts 1 and 2 only:
        // for (Animal a : animals) {

            // Part 1: 
            // sb.append(a.ride());
            
            // Part 2:
            // sb.append(Animal.ride(a));
            // sb.append("\n");
        // }

        // Part 3 only:
        RideVisitor rv = new RideVisitor();
        for (Animal a : animals) {
            System.out.println(a.accept(rv));
        }

        return sb.toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
